Fullchord changes
scuffed56/SCUFFED5.0 pull request #13
Opened 2023-01-27 15:44 UTC by Fullchord

-rewrote civ button logic to prevent bugs/abuse
-the removed ability to send civs to AI
-changed localization for game rules regarding Poland to make them clear
-changed the order of the game rules to put emphasis on the host tool
-you can now build aa in allies
-removed pp cost from leadership and social laws

2023-01-27 23:06 UTC, atomicplan666 requested changes
Fix the typo and the localization for the rules and then we good

2023-01-27 23:06 UTC, atomicplan666 commented on common/ideas/r56i_laws_social.txt
> +				army_defence_factor = 0.05`
nice typo

2023-01-27 23:06 UTC, atomicplan666 commented on localisation/english/replace/r56_game_rules_l_english.yml
> + PLAYER_POLAND_DESC:0 "Starts Poland off with default division count balanced for when players are on Poland"
The rule should say 
Disabled: "Poland is set to scuffed default"
Enabled: "If a PLAYER is on Poland then set to balanced mode"

2023-01-27 23:06 UTC, atomicplan666 commented on localisation/english/replace/r56_game_rules_l_english.yml
> + PLAYER_POLAND_DESC:0 "Starts Poland off with default division count balanced for when players are on Poland"
The game rule that turns Poland into "balanced mode" should not detect if there is a player or not (in my humble opinion). This should be left to the host's discretion.

2023-01-28 00:10 UTC, atomicplan666 approved these changes
looks good

2023-01-28 01:37 UTC, Juddur reviewed
YEs

2023-01-28 01:43 UTC, Juddur approved these changes

2023-01-28 01:45 UTC, merged