TCDTF Greece RT56
scuffed56/SCUFFED5.0 pull request #2
Opened 2023-01-18 23:48 UTC by xfrenzzyy

- Fixed the Cruiser bonuses so they actually work
- Added cruiser subs because they are in base game tree, but not in 56 tree.

2023-01-18 23:49 UTC, atomicplan666 commented on common/national_focus/r56_greece.txt
> +				category = ca_tech
What are these categories?

2023-01-21 05:09 UTC, Fullchord requested changes
These are overall good changes. Just a few areas feel overturned. Doing small changes is always best over drastic changes. With my proposed changes, this change would be much better. GJ!

2023-01-21 05:09 UTC, Fullchord commented on common/national_focus/saudi_arabia.txt
> +		cost = 5
Ghost went through the entire saudi tree and already rebalanced it these changes feel overturning

2023-01-21 05:09 UTC, Fullchord commented on common/national_focus/r56_greece.txt
>                }
Changing these to 4 mills feels like buffing this path better than the other and feels un-necessary

2023-01-21 05:09 UTC, Fullchord commented on common/national_focus/r56_greece.txt
> -		cost = 11.5
Changing this to 10 feels better for the buff (mby add 5 defenses on the core territory?)

2023-01-21 05:09 UTC, Fullchord commented on common/national_focus/colombia.txt
> -				infrastructure > 3
This was a cool mechanic and removing feels pointless

2023-01-21 18:20 UTC, xfrenzzyy commented on common/national_focus/r56_greece.txt
> +				category = ca_tech
Copied these from Italy tree, these give bonuses to cruisers, tested them and that's what they did.

2023-01-21 18:22 UTC, xfrenzzyy commented on common/ideas/portugal.txt
> +				industrial_capacity_dockyard = 0.15
Jud said the issue about these focuses are that they are too long it feel underwhelming, he thought a good idea was to bring it down to 70 days and a little more dockyard output to make the focuses worth taking.

2023-01-21 18:37 UTC, Fullchord commented on common/ideas/portugal.txt
> +				industrial_capacity_dockyard = 0.15
ya its not that large of a change so this could work for 70 days

2023-01-21 18:40 UTC, xfrenzzyy commented on common/national_focus/congo.txt
> +				ahead_reduction = 1
Fixed the air bonus so it actually works, the year bonus is whatever. My idea was to allow a Congo player to be able to rush air somewhat effectively. Wouldn't oppose bringing it back down to the previous bonus, up to you guys.

2023-01-21 18:40 UTC, xfrenzzyy commented on common/national_focus/congo.txt
> +				ahead_reduction = 1
Same as other review.

2023-01-21 18:47 UTC, Fullchord commented on common/national_focus/congo.txt
> +				ahead_reduction = 1
this feels over tuned and does not need to be added

2023-01-21 18:47 UTC, Fullchord commented on common/national_focus/congo.txt
> +				ahead_reduction = 1
this feels over tuned and does not need to be added

2023-01-21 18:54 UTC, xfrenzzyy commented on common/national_focus/colombia.txt
> -				infrastructure > 3
Actually is a cool mechanic since the industry tree is based around this mechanic. Could ignore that change.

2023-01-21 18:58 UTC, xfrenzzyy commented on common/national_focus/portugal.txt
> -		cost = 10
I didn't add any steel to this focus just changed the time it takes to do it. Juddy said the issue with this tree is that it overstacks infrastructure, so I'd say another change to this is just remove the infrastructure from the focus and keep it as 35 days.

2023-01-21 19:08 UTC, xfrenzzyy commented on common/national_focus/r56_greece.txt
>                }
The issue with the other paths in this tree are they are made for singleplayer really because they ask for land from major powers which is really only a singleplayer idea type of concept. There's a few way to fix those paths, as for this focus though you could make it a 35 day focus because it only gives 2 mils which is lackluster. Or you could possibly add a mil construction speed bonus, but that could make the tree somewhat unbalanced since they get a construction speed bonuses within this path. So, I think you could drop the focus to 35 days and keep it at 2 mils, or put it back to 70 days and give it an extra factory.

2023-01-21 19:13 UTC, xfrenzzyy commented on common/national_focus/r56_greece.txt
> -		cost = 11.5
The issue with this focus is that it just adds forts. If it adds fort construction speed then it would be worth, but most of the forts that are placed with this focus aren't really placed in useful areas. So, I think a fix for this focus is add fort construction speed and keep it 70 days.

2023-01-21 19:14 UTC, xfrenzzyy commented on common/national_focus/saudi_arabia.txt
> +		cost = 5
I didn't know Ghost went through the tree, in that case ignore these changes for Saudi.

2023-01-21 19:16 UTC, xfrenzzyy commented on common/national_focus/congo.txt
> +				ahead_reduction = 1
I agree

2023-01-21 19:24 UTC, xfrenzzyy commented on common/national_focus/congo.txt
> +        cost = 5
The issue with that is Congo has practically no focuses that give civs, so I think for this nation to be useful and playable these focuses should give at least 3 civs for 70 days. There's only 2 focuses that give civs, so this focus should stay how it is in my opinion.

2023-01-21 19:54 UTC, atomicplan666 commented on common/national_focus/congo.txt
> +				ahead_reduction = 1
For the Congo?? Who cares about the congo?

2023-01-21 20:00 UTC, xfrenzzyy commented on common/national_focus/congo.txt
> +				ahead_reduction = 1
I see the congo played sometimes, my idea was just to fix focuses so they actually work, the 1 year ahead doesn't matter to me it was just a copy and paste.

2023-01-21 20:02 UTC, atomicplan666 commented on common/national_focus/r56_greece.txt
> -		cost = 11.5
12 forts. that's all it adds. I think making this focus 35 days is fine.

2023-01-21 20:37 UTC, xfrenzzyy commented on common/national_focus/r56_greece.txt
> -		cost = 11.5
Yea that was kind of the point to putting it to 35 days, because it is really just forts.

2023-01-22 01:45 UTC, Fullchord requested changes

2023-01-22 04:13 UTC, xfrenzzyy commented on common/national_focus/r56_greece.txt
> +				category = ca_tech
This is the updated naval system. I just removed the ca_tech from the focus, so it looks better because it essentially does the same thing.

2023-01-22 17:05 UTC, xfrenzzyy commented
Changes are done.

2023-01-23 18:23 UTC, Fullchord approved these changes
I still feel the changes to Saudi Arabia are a bit much, but lets play test this and go from there!

2023-01-23 18:34 UTC, xfrenzzyy commented
The saudi changes arent as big/impactful as u may think, it just helps their early game industry since they have base game industry tree. Saudi usually doesnt touch their base game industry tree until 39 because their political tree is too important and kind of long too. I think these changes of adding 1 civ, 2 mils, and 1 dockyard in their tree will help, but not be too much.

2023-01-24 01:36 UTC, Juddur approved these changes

2023-01-27 23:11 UTC, atomicplan666 approved these changes
Looks good, let's see how it turns out.

2023-01-27 23:11 UTC, merged