TCDTF Poland
scuffed56/SCUFFED5.0 pull request #37
Opened 2023-02-21 02:22 UTC by Fullchord

-rebalanced ai, and player Poland starts
-made game rule no longer require a player
-changed a few Poland focuses to better templates

2023-02-22 14:30 UTC, Juddur approved these changes
Just redoes what poland already does

2023-02-24 19:12 UTC, xfrenzzyy reviewed
Seems like another Poland AI buff unless I'm reading these changes wrong.

2023-02-25 04:27 UTC, atomicplan666 requested changes

2023-02-25 04:27 UTC, atomicplan666 commented on common/on_actions/pol_on_actions.txt
> +					load_oob = "POL_1936_ai"
If has game rule player poland then load ai oob? doesn't make sense to me

2023-02-25 04:27 UTC, atomicplan666 commented on common/on_actions/pol_on_actions.txt
> +					load_oob = "POL_1936_player"
backwards?

2023-02-25 04:27 UTC, atomicplan666 commented on history/units/POL_1936_player.txt
> +	division= {
Why are there brackets added and deleted in this way?

2023-02-25 16:32 UTC, Endsiegg commented on common/on_actions/pol_on_actions.txt
> +					load_oob = "POL_1936_ai"
Seems like it backwards

2023-02-25 16:42 UTC, Endsiegg requested changes
UNDO ALL SUPER BUFFS TO POLAND AGAIN

2023-02-25 16:42 UTC, Endsiegg commented on common/national_focus/poland.txt
> +				amount = 3000
AI does not need more equipment.

2023-02-25 16:42 UTC, Endsiegg commented on common/national_focus/poland.txt
> +					artillery = { x = 0 y = 1 }
More Arty?

2023-02-25 16:42 UTC, Endsiegg commented on common/on_actions/pol_on_actions.txt
> +						amount = 13000
so now 4k more equipment?

2023-02-25 16:42 UTC, Endsiegg commented on history/units/POL_1936_player.txt
> +		start_equipment_factor = 0.8
Does not need double starting, we talked about this being an issue.

2023-02-25 16:42 UTC, Endsiegg commented on history/units/POL_1936_player.txt
> +		start_equipment_factor = 0.8
Same as above

2023-02-25 16:42 UTC, Endsiegg commented on history/units/POL_1936_player.txt
> +		start_equipment_factor = 0.8
Same as above

2023-02-25 16:42 UTC, Endsiegg commented on history/units/POL_1936_player.txt
> +	}
Why the hell are these doubled???

2023-02-25 16:42 UTC, Endsiegg commented on history/units/POL_1936_player.txt
> +		start_equipment_factor = 0.8 #0.6
Again? wtf is your obsession with buffing poland

2023-02-25 16:42 UTC, Endsiegg commented on history/units/POL_1936_player.txt
> +		start_equipment_factor = 0.8 #0.6
0.3 to 0.8 What in the world

2023-02-25 16:42 UTC, Endsiegg commented on history/units/POL_1936_player.txt
> +		start_equipment_factor = 0.6
I see doubles everywhere, stop secretly buffing shit

2023-02-26 15:50 UTC, atomicplan666 commented
This update essentially removes the option for hosts to debuff Poland. Why would a change like this be needed?

2023-02-26 15:52 UTC, atomicplan666 commented
> This update essentially removes the option for hosts to debuff Poland. Why would a change like this be needed?

Not like hosts could even control Poland to begin with. Which hosts should be allowed to do.

2023-02-26 19:57 UTC, Fullchord commented
People did not like the chnages

2023-02-26 19:57 UTC, closed without merging